'use strict';

const VERSION = '1.0.0';

// ANSI colors
const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
  bgRed: '\x1b[41m',
  bgGreen: '\x1b[42m',
  bgYellow: '\x1b[43m',
};

function noColor() {
  const nc = {};
  for (const k of Object.keys(c)) nc[k] = '';
  return nc;
}

const SEV_CONFIG = {
  CRITICAL: { icon: '✗', color: 'red', bg: 'bgRed' },
  HIGH:     { icon: '✗', color: 'red' },
  MEDIUM:   { icon: '✗', color: 'yellow' },
  LOW:      { icon: '~', color: 'cyan' },
  INFO:     { icon: 'ℹ', color: 'blue' },
  PASS:     { icon: '✓', color: 'green' },
};

function gradeColor(grade, col) {
  if (grade === 'A') return col.green;
  if (grade === 'B') return col.green;
  if (grade === 'C') return col.yellow;
  if (grade === 'D') return col.red;
  return col.red;
}

function formatTerminal(results, useColor = true) {
  const col = useColor ? c : noColor();
  const lines = [];
  const divider = col.dim + '─'.repeat(50) + col.reset;

  lines.push('');
  lines.push(`  ${col.bold}🛡️  0xAudit Security Scanner v${VERSION}${col.reset}`);
  lines.push('');
  lines.push(`  ${col.bold}Target:${col.reset} ${results.target}`);
  lines.push(`  ${col.bold}Score:${col.reset}  ${gradeColor(results.grade, col)}${col.bold}${results.grade} (${results.score}/100)${col.reset}`);
  lines.push(`  ${col.dim}Scan time: ${results.scanDuration}ms${col.reset}`);
  lines.push('');
  lines.push(`  ${divider}`);

  const severities = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
  for (const sev of severities) {
    const items = results.findings.filter(f => f.severity === sev);
    if (items.length === 0) continue;

    const cfg = SEV_CONFIG[sev];
    const sevColor = col[cfg.color] || '';
    lines.push('');
    lines.push(`  ${sevColor}${col.bold}${sev} (${items.length}):${col.reset}`);
    for (const item of items) {
      lines.push(`    ${sevColor}${cfg.icon}${col.reset} ${item.title}`);
      if (item.recommendation) {
        lines.push(`      ${col.dim}→ ${item.recommendation}${col.reset}`);
      }
    }
  }

  // Show passes summary
  const passes = results.findings.filter(f => f.severity === 'PASS');
  if (passes.length > 0) {
    lines.push('');
    lines.push(`  ${col.green}${col.bold}PASSED (${passes.length}):${col.reset}`);
    for (const item of passes) {
      lines.push(`    ${col.green}✓${col.reset} ${item.title}`);
    }
  }

  lines.push('');
  lines.push(`  ${divider}`);
  lines.push(`  ${col.bold}Full audit?${col.reset} Visit ${col.cyan}https://0-x-audit.com${col.reset}`);
  lines.push(`  ${col.dim}or connect via MCP: mcp.0-x-audit.com${col.reset}`);
  lines.push('');

  return lines.join('\n');
}

function formatJSON(results) {
  return JSON.stringify(results, null, 2);
}

function formatMarkdown(results) {
  const lines = [];
  lines.push(`# 🛡️ 0xAudit Security Report`);
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Target | ${results.target} |`);
  lines.push(`| Score | **${results.grade}** (${results.score}/100) |`);
  lines.push(`| Date | ${results.timestamp} |`);
  lines.push(`| Duration | ${results.scanDuration}ms |`);
  lines.push('');

  const severities = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
  for (const sev of severities) {
    const items = results.findings.filter(f => f.severity === sev);
    if (items.length === 0) continue;
    lines.push(`## ${sev} (${items.length})`);
    lines.push('');
    for (const item of items) {
      lines.push(`- **${item.title}**`);
      if (item.description) lines.push(`  - ${item.description}`);
      if (item.recommendation) lines.push(`  - 💡 ${item.recommendation}`);
    }
    lines.push('');
  }

  const passes = results.findings.filter(f => f.severity === 'PASS');
  if (passes.length > 0) {
    lines.push(`## ✅ Passed (${passes.length})`);
    lines.push('');
    for (const item of passes) {
      lines.push(`- ${item.title}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [0xAudit Scanner](https://0-x-audit.com)*');

  return lines.join('\n');
}

function formatReport(results, format = 'terminal', disableColor = false) {
  switch (format) {
    case 'json': return formatJSON(results);
    case 'md':
    case 'markdown': return formatMarkdown(results);
    default: return formatTerminal(results, !disableColor);
  }
}

module.exports = { formatReport };
